name: gwebplugin
main: com.gvision.gwebplugin.Plugin
version: ${project.version}
api-version: 1.21
description: Test plugin
commands:
  gweb:
    description: gwebplugin kommando
    usage: /gweb [reload]
